### ISSUE TITLE
L mod L mans fix up 

### ISSUE THREAD

**Issue by curvabayoyayo** [Cameronwasnthere/Strange-Berries#5]
Fix up bossman ...----,,,----

**Comment by Cameronwasnthere** [comment]
What's the issue?

**Comment by curvabayoyayo** [comment]
KEEP IT LEMON 
![image](https://github.com/Cameronwasnthere/Strange-Berries/assets/149120678/1b34e0c0-df79-44d2-81d0-b30df0e9c354)

**Comment by curvabayoyayo** [comment]
- [ ] 
```python
print("curwa bayoyao")

```

**Comment by Cameronwasnthere** [comment]
Closing as no issue was presented apart from yourself 

_I'm joking, he's a friend of mine for anyone who sees this_
